### ISSUE TITLE
Exception on change.GitPoller

### ISSUE THREAD

**Issue by jacky-chuang** [python/buildmaster-config#13]
Hi,

            I use Buildbot ( 0.9.8 ) and Twisted (==17.5.0) to run git poller,

            Config is below.

       c['change_source'].append(changes.GitPoller(
        repourl='git@172.23.45.81:/home/git/201701_postrack_swfw_app', branch='master',pollinterval=300, pollAtLaunch=True,
        gitbin="C:\\Program Files\\Git\\cmd\\git.exe",
        encoding="big5"))

       But it always to get the following exception :
      Can anybody tell what’s going wrong ? thanks!

      Jacky

2017-06-26 11:49:08+0800 [-] while polling for changes
                Traceback (most recent call last):
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 459, in callback
                    self._startRunCallbacks(result)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
                    self._runCallbacks()
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
                    current.result = callback(current.result, *args, **kw)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
                    _inlineCallbacks(r, g, deferred)
                --- <exception caught here> ---
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
                    result = g.send(result)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 190, in poll
                    path=self.workdir)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\buildbot\changes\gitpoller.py", line 357, in _dovccmd
                    path=encodeArg(path), env=os.environ)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 174, in getProcessOutputAndValue
                    reactor)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\utils.py", line 28, in _callProtocolWithDeferred
                    reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\posixbase.py", line 353, in spawnProcess
                    return Process(self, processProtocol, executable, args, env, path)
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 217, in __init__
                    doCreate()
                  File "d:\jacky\buildbot_virtualenv\buildbot\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 214, in doCreate
                    command, cmdline, None, None, 1, flags, env, path, StartupInfo)
                builtins.TypeError: Objects of type 'bytes' can not be converted to Unicode.

**Comment by zware** [comment]
@jacky-chuang This repository is just the config for buildbot.python.org/all; you're looking for the [Buildbot](https://github.com/buildbot/buildbot) repository.
