### ISSUE TITLE
Unauthorised login from cstratak-RHEL7-aarch6

### ISSUE THREAD

**Issue by pablogsal** [python/buildmaster-config#279]
Seems that  the builder `cstratak-RHEL7-aarch64` doesn't have the correct credentials. CC: @stratakis 

```
2021-09-21 10:45:54+0000 [Broker,40,10.132.169.157] invalid login from unknown user 'cstratak-RHEL7-aarch64'
2021-09-21 10:45:54+0000 [Broker,40,10.132.169.157] Peer will receive following PB traceback:
2021-09-21 10:45:54+0000 [Broker,40,10.132.169.157] Unhandled Error
        Traceback (most recent call last):
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/cred/portal.py", line 117, in login
            return maybeDeferred(
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 191, in maybeDeferred
            result = f(*args, **kwargs)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1909, in unwindGenerator
            return _cancellableInlineCallbacks(gen)  # type: ignore[unreachable]
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1816, in _cancellableInlineCallbacks
            _inlineCallbacks(None, gen, status)
        --- <exception caught here> ---
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
            result = current_context.run(gen.send, result)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/pbmanager.py", line 198, in requestAvatarId
            raise error.UnauthorizedLogin()
        twisted.cred.error.UnauthorizedLogin:
```

**Comment by stratakis** [comment]
Oops I've decommissioned that worker, however I let the VM and the process running. Turned it off now. Do you still see those logs?

**Comment by pablogsal** [comment]
Yeah, seems that this is gone!
