### ISSUE TITLE
AttributeError when stopping the buildbot server: 'NoneType' object has no attribute 'insubstantiate'

### ISSUE THREAD

**Issue by vstinner** [python/buildmaster-config#460]
```
2024-01-25 12:01:17+0000 [-] Initiating clean shutdown
2024-01-25 12:01:17+0000 [-]  <Build ARM64 MacOS M1 Refleaks NoGIL 3.x number:29 results:success>: stopping build: Master Shutdown 5
2024-01-25 12:01:17+0000 [-]  <Build AMD64 Ubuntu 3.x number:5660 results:success>: stopping build: Master Shutdown 5
2024-01-25 12:01:17+0000 [-] Unhandled error in Deferred:
2024-01-25 12:01:17+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/util/service.py", line 70, in disownServiceParent
            yield self.parent.removeService(self)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/application/service.py", line 313, in removeService
            return service.stopService()
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2256, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2168, in _cancellableInlineCallbacks
            _inlineCallbacks(None, gen, status, _copy_context())
        --- <exception caught here> ---
          File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/master.py", line 334, in call_after_signal
            yield self.disownServiceParent()
          File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/util/service.py", line 70, in disownServiceParent
            yield self.parent.removeService(self)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
            result = context.run(gen.send, result)
          File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/master.py", line 360, in stopService
            yield self.botmaster.cleanShutdown(quickMode=True, stopReactor=False)
        builtins.AttributeError: 'NoneType' object has no attribute 'insubstantiate'     
```

pip freeze **after** the server was restarted (but versions should be the same):

```
$ venv/bin/python -m pip freeze
alembic==1.13.1
attrs==23.2.0
autobahn==23.6.2
Automat==22.10.0
blinker==1.7.0
buildbot==3.10.1
buildbot-console-view==3.10.1
buildbot-grid-view==3.10.1
buildbot-profiler==1.3.1
buildbot-waterfall-view==3.10.1
buildbot-worker==3.10.1
buildbot-wsgi-dashboards==3.10.1
buildbot-www==3.10.1
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
constantly==23.10.4
croniter==2.0.1
cryptography==41.0.7
Flask==3.0.0
future==0.18.3
greenlet==3.0.3
hyperlink==21.0.0
idna==3.6
importlib-metadata==7.0.1
importlib-resources==6.1.1
incremental==22.10.0
itsdangerous==2.1.2
Jinja2==3.1.3
klein==23.12.0
Mako==1.3.0
MarkupSafe==2.1.3
msgpack==1.0.7
packaging==23.2
psutil==5.9.7
psycopg2==2.9.9
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
PyJWT==2.8.0
pyOpenSSL==23.3.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
requests==2.31.0
sentry-sdk==1.39.2
service-identity==24.1.0
six==1.16.0
SQLAlchemy==1.4.51
treq==23.11.0
Tubes==0.2.1
Twisted==23.10.0
txaio==23.1.1
typing_extensions==4.9.0
unidiff==0.7.5
urllib3==2.1.0
Werkzeug==3.0.1
zipp==3.17.0
zope.interface==6.1
```

**Comment by vstinner** [comment]
I didn't see this error recently. buildbot was upgraded to 4.0 in the meanwhile. I close the issue.
